# .github/workflows/selenium-test.yml

name: Run Simple Selenium Test

on:
  
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # This allows manual or API-triggered runs

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies (Selenium)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      # Run the Selenium test script
      - name: Run Selenium test
        run: python simple_selenium_test.py
